services:
  postgres:
    image: postgres:17.2-bullseye
    container_name: adventofsql-postgres
    ports:
      - 6432:5432
    volumes:
      - adventofsql-2024:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=santas_helper
      - POSTGRES_DB=santa_workshop
volumes:
  adventofsql-2024:
